DEBUG = True
SQLALCHEMY_ECHO = True  # 打印sql语句
SERVER_PORT = 9001
SQLALCHEMY_DATABASE_URI = 'mysql://root:xxxian527@127.0.0.1/mysql'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ENCODING = "UTF-8"  # 数据库的编码
RELEASE_VERSION = "0.0.1"
